spring:
  application:
    name: Digital active

  docker:
    compose:
      enabled: true


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Sweets}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:jasur1803}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false



application:
  rca:
    private-key: ${PRIVATE_KEY_PATH:classpath:keys/private_key.pem}
    public-key: ${PUBLIC_KEY_PATH:classpath:keys/public_key.pem}

springdoc:
  swagger-ui:
    path:/swagger-ui.html

minio:
  url: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: sweets