spring:
  profiles:
    active: dev


  mail:
    host: smtp.gmail.com
    port: 587
    username: jasurshodmonov21020@gmail.com
    password: wbdl oegp oefj wafx
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true